/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "light_controller.v:1.1-65.10" *)
module light_controller(set_light_color, clk, car_has_arrived, current_light_state, street_light_controller);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  (* force_downto = 32'd1 *)
  (* src = "light_controller.v:49.17-49.39|/usr/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire [9:0] _096_;
  (* force_downto = 32'd1 *)
  (* src = "light_controller.v:43.40-43.63|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [12:0] _097_;
  (* force_downto = 32'd1 *)
  (* src = "light_controller.v:43.40-43.63|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [12:0] _098_;
  (* force_downto = 32'd1 *)
  (* src = "light_controller.v:48.26-48.44|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [12:0] _099_;
  (* force_downto = 32'd1 *)
  (* src = "light_controller.v:48.26-48.44|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [12:0] _100_;
  (* src = "light_controller.v:14.11-14.26" *)
  input car_has_arrived;
  wire car_has_arrived;
  (* src = "light_controller.v:11.11-11.14" *)
  input clk;
  wire clk;
  (* src = "light_controller.v:20.17-20.36" *)
  input [1:0] current_light_state;
  wire [1:0] current_light_state;
  (* src = "light_controller.v:28.16-28.32" *)
  reg [12:0] green_light_time = 13'h0000;
  (* src = "light_controller.v:7.22-7.37" *)
  output [1:0] set_light_color;
  reg [1:0] set_light_color;
  (* src = "light_controller.v:25.11-25.34" *)
  input street_light_controller;
  wire street_light_controller;
  (* src = "light_controller.v:27.16-27.26" *)
  reg [12:0] yield_time = 13'h0000;
  assign _050_ = green_light_time[1] & green_light_time[0];
  assign _098_[2] = _050_ ^ green_light_time[2];
  assign _051_ = _050_ & green_light_time[2];
  assign _098_[3] = _051_ ^ green_light_time[3];
  assign _052_ = ~(green_light_time[3] & green_light_time[2]);
  assign _053_ = _050_ & ~(_052_);
  assign _098_[4] = _053_ ^ green_light_time[4];
  assign _054_ = _053_ & green_light_time[4];
  assign _098_[5] = _054_ ^ green_light_time[5];
  assign _055_ = ~(green_light_time[5] & green_light_time[4]);
  assign _056_ = _053_ & ~(_055_);
  assign _098_[6] = _056_ ^ green_light_time[6];
  assign _057_ = _056_ & green_light_time[6];
  assign _098_[7] = _057_ ^ green_light_time[7];
  assign _058_ = ~(_055_ | _087_);
  assign _059_ = ~(_058_ & _053_);
  assign _098_[8] = ~(_059_ ^ green_light_time[8]);
  assign _060_ = green_light_time[8] & ~(_059_);
  assign _098_[9] = _060_ ^ green_light_time[9];
  assign _061_ = ~(_059_ | _090_);
  assign _098_[10] = _061_ ^ green_light_time[10];
  assign _062_ = _061_ & green_light_time[10];
  assign _098_[11] = _062_ ^ green_light_time[11];
  assign _063_ = ~(green_light_time[11] & green_light_time[10]);
  assign _064_ = _063_ | _090_;
  assign _065_ = ~(_064_ | _059_);
  assign _098_[12] = _065_ ^ green_light_time[12];
  assign _099_[0] = ~yield_time[0];
  assign _066_ = ~yield_time[10];
  assign _067_ = ~(yield_time[9] & yield_time[8]);
  assign _068_ = yield_time[7] & yield_time[6];
  assign _069_ = ~(yield_time[5] & yield_time[4]);
  assign _070_ = _068_ & ~(_069_);
  assign _071_ = yield_time[3] & yield_time[2];
  assign _072_ = ~(yield_time[1] & yield_time[0]);
  assign _073_ = _072_ | ~(_071_);
  assign _074_ = _070_ & ~(_073_);
  assign _075_ = _074_ & ~(_067_);
  assign _076_ = _075_ & ~(_066_);
  assign _096_[8] = _076_ ^ yield_time[11];
  assign _077_ = _075_ ^ _066_;
  assign _096_[7] = ~_077_;
  assign _078_ = yield_time[4] & ~(_073_);
  assign _079_ = ~(_078_ ^ yield_time[5]);
  assign _096_[2] = ~_079_;
  assign _080_ = _073_ | _069_;
  assign _096_[3] = ~(_080_ ^ yield_time[6]);
  assign _081_ = _071_ & ~(_072_);
  assign _096_[1] = _081_ ^ yield_time[4];
  assign _082_ = current_light_state[1] & current_light_state[0];
  assign _083_ = green_light_time[1] | green_light_time[0];
  assign _084_ = green_light_time[2] | ~(green_light_time[3]);
  assign _085_ = _084_ | _083_;
  assign _086_ = green_light_time[4] | ~(green_light_time[5]);
  assign _087_ = ~(green_light_time[7] & green_light_time[6]);
  assign _088_ = _087_ | _086_;
  assign _089_ = _088_ | _085_;
  assign _090_ = ~(green_light_time[9] & green_light_time[8]);
  assign _091_ = green_light_time[11] | green_light_time[10];
  assign _092_ = _091_ | _090_;
  assign _093_ = _092_ | green_light_time[12];
  assign _005_ = _093_ | _089_;
  assign _006_ = yield_time[2] & ~(_072_);
  assign _096_[0] = _006_ ^ yield_time[3];
  assign _007_ = yield_time[6] & ~(_080_);
  assign _008_ = ~(_007_ ^ yield_time[7]);
  assign _096_[4] = ~_008_;
  assign _009_ = ~(_081_ & _070_);
  assign _010_ = _009_ ^ yield_time[8];
  assign _096_[5] = ~_010_;
  assign _011_ = yield_time[8] & ~(_009_);
  assign _012_ = ~(_011_ ^ yield_time[9]);
  assign _096_[6] = ~_012_;
  assign _013_ = ~(yield_time[11] & yield_time[10]);
  assign _014_ = _013_ | _067_;
  assign _015_ = _074_ & ~(_014_);
  assign _016_ = ~(_015_ ^ yield_time[12]);
  assign _096_[9] = ~_016_;
  assign _001_ = current_light_state[0] & ~(current_light_state[1]);
  assign _017_ = yield_time[1] & yield_time[0];
  assign _100_[2] = ~(_072_ ^ yield_time[2]);
  assign _018_ = _100_[2] | ~(_096_[0]);
  assign _019_ = _017_ & ~(_018_);
  assign _020_ = _096_[1] | ~(_079_);
  assign _021_ = _008_ | _096_[3];
  assign _022_ = _021_ | _020_;
  assign _023_ = _019_ & ~(_022_);
  assign _024_ = _012_ | _010_;
  assign _025_ = _096_[7] | _096_[8];
  assign _026_ = _025_ | _024_;
  assign _027_ = _026_ | _016_;
  assign _028_ = _023_ & ~(_027_);
  assign _029_ = _096_[8] & ~(_016_);
  assign _030_ = _096_[9] & ~(_096_[8]);
  assign _031_ = _077_ & ~(_012_);
  assign _032_ = _010_ | _008_;
  assign _033_ = _031_ & ~(_032_);
  assign _034_ = _079_ & ~(_096_[3]);
  assign _035_ = ~(_096_[0] | _096_[1]);
  assign _036_ = _034_ & ~(_035_);
  assign _037_ = _034_ & ~(_036_);
  assign _038_ = _033_ & ~(_037_);
  assign _039_ = _077_ & ~(_038_);
  assign _040_ = _030_ & ~(_039_);
  assign _041_ = _040_ | _029_;
  assign _004_ = _041_ | _028_;
  assign _003_ = _001_ | _082_;
  assign _000_ = _082_ & ~(street_light_controller);
  assign _042_ = _082_ | street_light_controller;
  assign _043_ = current_light_state[1] | current_light_state[0];
  assign _044_ = _043_ | _042_;
  assign _045_ = _000_ & _005_;
  assign _046_ = _044_ & ~(_045_);
  assign _047_ = _082_ & street_light_controller;
  assign _048_ = _001_ & ~(_004_);
  assign _049_ = _048_ | _047_;
  assign _002_ = _046_ & ~(_049_);
  assign _094_ = current_light_state[1] | ~(current_light_state[0]);
  assign _095_ = ~(current_light_state[1] ^ current_light_state[0]);
  assign _100_[1] = yield_time[1] ^ yield_time[0];
  assign _097_[0] = ~green_light_time[0];
  assign _098_[1] = green_light_time[1] ^ green_light_time[0];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_002_)
      if (_003_) set_light_color[1] <= 1'h0;
      else set_light_color[1] <= _094_;
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_002_)
      if (_082_) set_light_color[0] <= 1'h1;
      else set_light_color[0] <= _095_;
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[0] <= 1'h0;
      else yield_time[0] <= _099_[0];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[1] <= 1'h0;
      else yield_time[1] <= _100_[1];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[2] <= 1'h0;
      else yield_time[2] <= _100_[2];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[3] <= 1'h0;
      else yield_time[3] <= _096_[0];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[4] <= 1'h0;
      else yield_time[4] <= _096_[1];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[5] <= 1'h0;
      else yield_time[5] <= _096_[2];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[6] <= 1'h0;
      else yield_time[6] <= _096_[3];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[7] <= 1'h0;
      else yield_time[7] <= _096_[4];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[8] <= 1'h0;
      else yield_time[8] <= _096_[5];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[9] <= 1'h0;
      else yield_time[9] <= _096_[6];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[10] <= 1'h0;
      else yield_time[10] <= _096_[7];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[11] <= 1'h0;
      else yield_time[11] <= _096_[8];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_001_)
      if (_004_) yield_time[12] <= 1'h0;
      else yield_time[12] <= _096_[9];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[0] <= 1'h0;
      else green_light_time[0] <= _097_[0];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[1] <= 1'h0;
      else green_light_time[1] <= _098_[1];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[2] <= 1'h0;
      else green_light_time[2] <= _098_[2];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[3] <= 1'h0;
      else green_light_time[3] <= _098_[3];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[4] <= 1'h0;
      else green_light_time[4] <= _098_[4];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[5] <= 1'h0;
      else green_light_time[5] <= _098_[5];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[6] <= 1'h0;
      else green_light_time[6] <= _098_[6];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[7] <= 1'h0;
      else green_light_time[7] <= _098_[7];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[8] <= 1'h0;
      else green_light_time[8] <= _098_[8];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[9] <= 1'h0;
      else green_light_time[9] <= _098_[9];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[10] <= 1'h0;
      else green_light_time[10] <= _098_[10];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[11] <= 1'h0;
      else green_light_time[11] <= _098_[11];
  (* src = "light_controller.v:35.5-63.8" *)
  always @(posedge clk)
    if (_000_)
      if (!_005_) green_light_time[12] <= 1'h0;
      else green_light_time[12] <= _098_[12];
  assign _097_[12:1] = green_light_time[12:1];
  assign _098_[0] = _097_[0];
  assign _099_[12:1] = yield_time[12:1];
  assign { _100_[12:3], _100_[0] } = { _096_, _099_[0] };
endmodule

(* top =  1  *)
(* src = "street_light_controller.v:1.1-99.10" *)
module street_light_controller(street_light1, street_light2, street_light3, street_light4, button_pushed, clk, reset);
  wire _00_;
  (* src = "street_light_controller.v:85.51-85.66" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "street_light_controller.v:6.11-6.24" *)
  input button_pushed;
  wire button_pushed;
  (* src = "street_light_controller.v:7.11-7.14" *)
  input clk;
  wire clk;
  (* src = "street_light_controller.v:15.15-15.35" *)
  wire [1:0] current_light_state1;
  (* src = "street_light_controller.v:16.15-16.35" *)
  wire [1:0] current_light_state2;
  (* src = "street_light_controller.v:17.15-17.35" *)
  wire [1:0] current_light_state3;
  (* src = "street_light_controller.v:18.15-18.35" *)
  wire [1:0] current_light_state4;
  (* src = "street_light_controller.v:11.9-11.42" *)
  wire east_west_street_light_controller;
  (* src = "street_light_controller.v:10.9-10.44" *)
  reg north_south_street_light_controller = 1'h0;
  (* src = "street_light_controller.v:13.9-13.23" *)
  wire patch_switches;
  (* src = "street_light_controller.v:8.11-8.16" *)
  input reset;
  wire reset;
  (* src = "street_light_controller.v:20.15-20.26" *)
  wire [3:0] startuptime;
  (* src = "street_light_controller.v:2.18-2.31" *)
  output [1:0] street_light1;
  wire [1:0] street_light1;
  (* src = "street_light_controller.v:3.18-3.31" *)
  output [1:0] street_light2;
  wire [1:0] street_light2;
  (* src = "street_light_controller.v:4.18-4.31" *)
  output [1:0] street_light3;
  wire [1:0] street_light3;
  (* src = "street_light_controller.v:5.18-5.31" *)
  output [1:0] street_light4;
  wire [1:0] street_light4;
  assign _02_ = ~(street_light3[0] & street_light1[0]);
  assign _03_ = street_light4[0] & street_light2[0];
  assign _04_ = _03_ ^ _02_;
  assign _05_ = ~(street_light3[1] & street_light1[1]);
  assign _06_ = street_light4[1] & street_light2[1];
  assign _07_ = _06_ ^ _05_;
  assign _00_ = _07_ | _04_;
  assign _01_ = ~north_south_street_light_controller;
  (* src = "street_light_controller.v:67.5-76.8" *)
  always @(posedge reset)
    north_south_street_light_controller <= 1'h1;
  (* src = "street_light_controller.v:78.5-90.8" *)
  always @(posedge button_pushed)
    if (!_00_) north_south_street_light_controller <= _01_;
  (* module_not_derived = 32'd1 *)
  (* src = "street_light_controller.v:22.22-28.6" *)
  light_controller LIGHT1 (
    .car_has_arrived(button_pushed),
    .clk(clk),
    .current_light_state(2'h0),
    .set_light_color(street_light1),
    .street_light_controller(north_south_street_light_controller)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "street_light_controller.v:38.22-44.6" *)
  light_controller LIGHT2 (
    .car_has_arrived(button_pushed),
    .clk(clk),
    .current_light_state(2'h3),
    .set_light_color(street_light2),
    .street_light_controller(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "street_light_controller.v:30.22-36.6" *)
  light_controller LIGHT3 (
    .car_has_arrived(button_pushed),
    .clk(clk),
    .current_light_state(2'h0),
    .set_light_color(street_light3),
    .street_light_controller(north_south_street_light_controller)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "street_light_controller.v:46.22-52.6" *)
  light_controller LIGHT4 (
    .car_has_arrived(button_pushed),
    .clk(clk),
    .current_light_state(2'h3),
    .set_light_color(street_light4),
    .street_light_controller(1'h0)
  );
  assign current_light_state1 = 2'h0;
  assign current_light_state2 = 2'h3;
  assign current_light_state3 = 2'h0;
  assign current_light_state4 = 2'h3;
  assign east_west_street_light_controller = 1'h0;
  assign patch_switches = north_south_street_light_controller;
  assign startuptime = 4'h0;
endmodule
